%Definisco la struttura della rete neurale LSTM: layer da
%inserire e opzioni di allenamento. 

numFeatures = size(XTrain3SD,1);  % tutte le feaures in input
numResponses = 10; % output = le 5 velocità
numHiddenUnits1 = 50;  
layersNP = [ ...
    sequenceInputLayer(numFeatures,'Name','Input')
    lstmLayer(numHiddenUnits1,'Name','Hidden')
    dropoutLayer(0.5,'Name','Dropout') 
    fullyConnectedLayer(numResponses)
    softmaxLayer('Name','SoftMax')
    classificationLayer('Name','Output')
    ];

optionsNP = trainingOptions('adam', ...
    'MaxEpochs',40,...
    'InitialLearnRate', 0.001, ...
    'GradientThreshold', 1, ...
    'ExecutionEnvironment',"auto",...
    'plots','training-progress', ...
    'ValidationData',{XTest3SD,YTest3}, ... %utilizzo come validation set quello di test, per vedere direttamente l'accuracy in test
    'ValidationFrequency',2, ...
    'Verbose',false);

netNP = trainNetwork(XTrain3SD,YTrain3,layersNP,optionsNP); %alleno la rete

%     'LearnRateSchedule','piecewise', ...
%     'LearnRateDropFactor',0.05, ...
%     'LearnRateDropPeriod',15, ...