function F = import_forces(filename, dataLines)
%IMPORTFILE Import data from a text file
%  F11 = IMPORTFILE(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as a table.
%
%  F11 = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  F11 = importfile("C:\Users\15 ek00004nl\Desktop\Trapano ML\Acquisizioni con accelerometri\15_01\FORZA\1\V1.txt", [6, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 2021-02-24 09:16:31

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [6, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["time", "Force_0", "Force_1"];
opts.VariableTypes = ["string", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "time", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "time", "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["Force_0", "Force_1"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["Force_0", "Force_1"], "DecimalSeparator", ",");
opts = setvaropts(opts, ["Force_0", "Force_1"], "ThousandsSeparator", ".");

% Import the data
F = readtable(filename, opts);

end