function [trainedClassifier, validationAccuracy] = trainClassifier_unfilt_NP_manualFeat(trainingData)
% [trainedClassifier, validationAccuracy] = trainClassifier(trainingData)
% Returns a trained classifier and its accuracy. This code recreates the
% classification model trained in Classification Learner app. Use the
% generated code to automate training the same model with new data, or to
% learn how to programmatically train models.
%
%  Input:
%      trainingData: A table containing the same predictor and response
%       columns as those imported into the app.
%
%  Output:
%      trainedClassifier: A struct containing the trained classifier. The
%       struct contains various fields with information about the trained
%       classifier.
%
%      trainedClassifier.predictFcn: A function to make predictions on new
%       data.
%
%      validationAccuracy: A double containing the accuracy in percent. In
%       the app, the History list displays this overall accuracy score for
%       each model.
%
% Use the code to train the model with new data. To retrain your
% classifier, call the function from the command line with your original
% data or new data as the input argument trainingData.
%
% For example, to retrain a classifier trained with the original data set
% T, enter:
%   [trainedClassifier, validationAccuracy] = trainClassifier(T)
%
% To make predictions with the returned 'trainedClassifier' on new data T2,
% use
%   yfit = trainedClassifier.predictFcn(T2)
%
% T2 must be a table containing at least the same predictor columns as used
% during training. For details, enter:
%   trainedClassifier.HowToPredict

% Auto-generated by MATLAB on 04-Mar-2021 14:52:31


% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'meanPsd_ax', 'meanPsd_ay', 'meanPsd_az', 'rmsPsd_ax', 'rmsPsd_ay', 'rmsPsd_az', 'stdPsd_ax', 'stdPsd_ay', 'stdPsd_az', 'meanFft_ax', 'meanFft_ay', 'meanFft_az', 'max_ax_top', 'max_ay_top', 'max_az_top', 'std_ax_top', 'std_ay_top', 'std_az_top'};
predictors = inputTable(:, predictorNames);
response = inputTable.velocity;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];

% Train a classifier
% This code specifies all the classifier options and trains the classifier.
classificationKNN = fitcknn(...
    predictors, ...
    response, ...
    'Distance', 'Cityblock', ...
    'Exponent', [], ...
    'NumNeighbors', 11, ...
    'DistanceWeight', 'Inverse', ...
    'Standardize', true, ...
    'ClassNames', categorical({'V1_N: 560 RPM'; 'V2_N: 780 RPM'; 'V3_N: 1200 RPM'; 'V4_N: 1900 RPM'; 'V5_N: 3000 RPM'; 'V1_P: 560 RPM'; 'V2_P: 780 RPM'; 'V3_P: 1200 RPM'; 'V4_P: 1900 RPM'; 'V5_P: 3000 RPM'}, {'V1_N: 560 RPM' 'V2_N: 780 RPM' 'V3_N: 1200 RPM' 'V4_N: 1900 RPM' 'V5_N: 3000 RPM' 'V1_P: 560 RPM' 'V2_P: 780 RPM' 'V3_P: 1200 RPM' 'V4_P: 1900 RPM' 'V5_P: 3000 RPM'}));

% Create the result struct with predict function
predictorExtractionFcn = @(t) t(:, predictorNames);
knnPredictFcn = @(x) predict(classificationKNN, x);
trainedClassifier.predictFcn = @(x) knnPredictFcn(predictorExtractionFcn(x));

% Add additional fields to the result struct
trainedClassifier.RequiredVariables = {'max_ax_top', 'max_ay_top', 'max_az_top', 'meanFft_ax', 'meanFft_ay', 'meanFft_az', 'meanPsd_ax', 'meanPsd_ay', 'meanPsd_az', 'rmsPsd_ax', 'rmsPsd_ay', 'rmsPsd_az', 'stdPsd_ax', 'stdPsd_ay', 'stdPsd_az', 'std_ax_top', 'std_ay_top', 'std_az_top'};
trainedClassifier.ClassificationKNN = classificationKNN;
trainedClassifier.About = 'This struct is a trained model exported from Classification Learner R2020a.';
trainedClassifier.HowToPredict = sprintf('To make predictions on a new table, T, use: \n  yfit = c.predictFcn(T) \nreplacing ''c'' with the name of the variable that is this struct, e.g. ''trainedModel''. \n \nThe table, T, must contain the variables returned by: \n  c.RequiredVariables \nVariable formats (e.g. matrix/vector, datatype) must match the original training data. \nAdditional variables are ignored. \n \nFor more information, see <a href="matlab:helpview(fullfile(docroot, ''stats'', ''stats.map''), ''appclassification_exportmodeltoworkspace'')">How to predict using an exported model</a>.');

% Extract predictors and response
% This code processes the data into the right shape for training the
% model.
inputTable = trainingData;
predictorNames = {'meanPsd_ax', 'meanPsd_ay', 'meanPsd_az', 'rmsPsd_ax', 'rmsPsd_ay', 'rmsPsd_az', 'stdPsd_ax', 'stdPsd_ay', 'stdPsd_az', 'meanFft_ax', 'meanFft_ay', 'meanFft_az', 'max_ax_top', 'max_ay_top', 'max_az_top', 'std_ax_top', 'std_ay_top', 'std_az_top'};
predictors = inputTable(:, predictorNames);
response = inputTable.velocity;
isCategoricalPredictor = [false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false];

% Perform cross-validation
partitionedModel = crossval(trainedClassifier.ClassificationKNN, 'KFold', 5);

% Compute validation predictions
[validationPredictions, validationScores] = kfoldPredict(partitionedModel);

% Compute validation accuracy
validationAccuracy = 1 - kfoldLoss(partitionedModel, 'LossFun', 'ClassifError');
